import 'package:get/get.dart';
import 'package:qtc_motoboy/app/modules/home/controllers/home_controller.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Corrida {
  HomeController cHome = Get.find();
/*
{
  "dataDacorrida": "13/13/2013",
  "precoDaGasolina": 4.55,
  "distanciaDaCorridaKm": 4.21,
  "precoCobradoPeloMotoboy": 45.5,
  "kmPorLitroVeiculo": 15.2,
  "valorMedioRevisaoVeiculo": 120.4,
  "kmMedioRevisaoVeiculo": 50.5,
  "valorTrocaDeOleo": 30.1,
  "kmMedioTrocaDeOleo": 50.5
} 
*/
  String? idCorrida;
  String? dataDacorrida;
  double? precoDaGasolinaNoDia;
  double? distanciaDaCorridaKm;
  double? precoCobradoPeloMotoboyNoDia;
  double? kmPorLitroVeiculoNoDia;
  double? valorMedioRevisaoVeiculoNoDia;
  double? kmMedioRevisaoVeiculoNoDia;
  double? valorTrocaDeOleoNoDia;
  double? kmMedioTrocaDeOleoNoDia;

  Corrida({
    required this.idCorrida,
    required this.dataDacorrida,
    required this.precoDaGasolinaNoDia,
    required this.distanciaDaCorridaKm,
    required this.precoCobradoPeloMotoboyNoDia,
    required this.kmPorLitroVeiculoNoDia,
    required this.valorMedioRevisaoVeiculoNoDia,
    required this.kmMedioRevisaoVeiculoNoDia,
    required this.valorTrocaDeOleoNoDia,
    required this.kmMedioTrocaDeOleoNoDia,
  });
  Corrida.fromJson(Map<String, dynamic> json) {
    idCorrida = json['idCorrida']?.toString();
    dataDacorrida = json['dataDacorrida']?.toString();
    precoDaGasolinaNoDia = json['precoDaGasolina']?.toDouble();
    distanciaDaCorridaKm = json['distanciaDaCorridaKm']?.toDouble();
    precoCobradoPeloMotoboyNoDia = json['precoCobradoPeloMotoboy']?.toDouble();
    kmPorLitroVeiculoNoDia = json['kmPorLitroVeiculo']?.toDouble();
    valorMedioRevisaoVeiculoNoDia = json['valorMedioRevisaoVeiculo']?.toDouble();
    kmMedioRevisaoVeiculoNoDia = json['kmMedioRevisaoVeiculo']?.toDouble();
    valorTrocaDeOleoNoDia = json['valorTrocaDeOleo']?.toDouble();
    kmMedioTrocaDeOleoNoDia = json['kmMedioTrocaDeOleo']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['idCorrida'] = idCorrida;
    data['dataDacorrida'] = dataDacorrida;
    data['precoDaGasolina'] = precoDaGasolinaNoDia;
    data['distanciaDaCorridaKm'] = distanciaDaCorridaKm;
    data['precoCobradoPeloMotoboy'] = precoCobradoPeloMotoboyNoDia;
    data['kmPorLitroVeiculo'] = kmPorLitroVeiculoNoDia;
    data['valorMedioRevisaoVeiculo'] = valorMedioRevisaoVeiculoNoDia;
    data['kmMedioRevisaoVeiculo'] = kmMedioRevisaoVeiculoNoDia;
    data['valorTrocaDeOleo'] = valorTrocaDeOleoNoDia;
    data['kmMedioTrocaDeOleo'] = kmMedioTrocaDeOleoNoDia;
    return data;
  }
}
