///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Corrida {
/*
{
  "id": "string",
  "dataHora": "DateTime",
  "percentualLucro": "string",
  "precoCombustivel": "string",
  "qtdkmPorLitro": "string",
  "distanciaDaCorrida": "string",
  "valorCobrado": "string",
  "diferencaFinal": "string"
} 
*/

  late String id;
  late String dataHora;
  late String percentualLucro;
  late String precoCombustivel;
  late String qtdkmPorLitro;
  late String distanciaDaCorrida;
  late String valorCobrado;
  late String diferencaFinal;

  Corrida({
    required this.id,
    required this.dataHora,
    required this.percentualLucro,
    required this.precoCombustivel,
    required this.qtdkmPorLitro,
    required this.distanciaDaCorrida,
    required this.valorCobrado,
    required this.diferencaFinal,
  });
  Corrida.fromJson(Map<String, dynamic> json) {
    id = json['id'].toString();
    dataHora = json['dataHora'].toString();
    percentualLucro = json['percentualLucro'].toString();
    precoCombustivel = json['precoCombustivel'].toString();
    qtdkmPorLitro = json['qtdkmPorLitro'].toString();
    distanciaDaCorrida = json['distanciaDaCorrida'].toString();
    valorCobrado = json['valorCobrado'].toString();
    diferencaFinal = json['diferencaFinal'].toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['dataHora'] = dataHora;
    data['percentualLucro'] = percentualLucro;
    data['precoCombustivel'] = precoCombustivel;
    data['qtdkmPorLitro'] = qtdkmPorLitro;
    data['distanciaDaCorrida'] = distanciaDaCorrida;
    data['valorCobrado'] = valorCobrado;
    data['diferencaFinal'] = diferencaFinal;
    return data;
  }
}
