///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Custos {
/*
{
  "precoCombustivel": "50"
} 
*/

  String? precoCombustivel;

  Custos({
    this.precoCombustivel,
  });
  Custos.fromJson(Map<String, dynamic> json) {
    precoCombustivel = json['precoCombustivel']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['precoCombustivel'] = precoCombustivel;
    return data;
  }
}
