///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Custos {
/*
{
  "precoGasolina": 4.55,
  "distanciaCorridaKm": 4.21,
  "valorInformadoMotoboy": 45.5
} 
*/

  double? precoGasolina;
  double? distanciaCorridaKm;
  double? valorInformadoMotoboy;

  Custos({
    this.precoGasolina,
    this.distanciaCorridaKm,
    this.valorInformadoMotoboy,
  });
  Custos.fromJson(Map<String, dynamic> json) {
    precoGasolina = json['precoGasolina']?.toDouble();
    distanciaCorridaKm = json['distanciaCorridaKm']?.toDouble();
    valorInformadoMotoboy = json['valorInformadoMotoboy']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['precoGasolina'] = precoGasolina;
    data['distanciaCorridaKm'] = distanciaCorridaKm;
    data['valorInformadoMotoboy'] = valorInformadoMotoboy;
    return data;
  }
}
