///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Veiculo {
/*
{
  "kmPorLitro": 15.2,
  "valorMedioRevisao": 120.4,
  "kmMedioRevisao": 50.5,
  "valorTrocaDeOleo": 30.1,
  "kmMedioTrocaDeOleo": 50.5
} 
*/

  double? kmPorLitro;
  double? valorMedioRevisao;
  double? kmMedioRevisao;
  double? valorTrocaDeOleo;
  double? kmMedioTrocaDeOleo;

  Veiculo({
    this.kmPorLitro,
    this.valorMedioRevisao,
    this.kmMedioRevisao,
    this.valorTrocaDeOleo,
    this.kmMedioTrocaDeOleo,
  });
  Veiculo.fromJson(Map<String, dynamic> json) {
    kmPorLitro = json['kmPorLitro']?.toDouble();
    valorMedioRevisao = json['valorMedioRevisao']?.toDouble();
    kmMedioRevisao = json['kmMedioRevisao']?.toDouble();
    valorTrocaDeOleo = json['valorTrocaDeOleo']?.toDouble();
    kmMedioTrocaDeOleo = json['kmMedioTrocaDeOleo']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['kmPorLitro'] = kmPorLitro;
    data['valorMedioRevisao'] = valorMedioRevisao;
    data['kmMedioRevisao'] = kmMedioRevisao;
    data['valorTrocaDeOleo'] = valorTrocaDeOleo;
    data['kmMedioTrocaDeOleo'] = kmMedioTrocaDeOleo;
    return data;
  }
}
