///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Veiculo {
/*
{
  "qtdkmPorLitro": "50"
} 
*/

  String? qtdkmPorLitro;

  Veiculo({
    this.qtdkmPorLitro,
  });
  Veiculo.fromJson(Map<String, dynamic> json) {
    qtdkmPorLitro = json['qtdkmPorLitro']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['qtdkmPorLitro'] = qtdkmPorLitro;
    return data;
  }
}
